### ISSUE TITLE
Output line numbers with gcode

### ISSUE THREAD

**Issue by winder** [NRSoft/GSharp#1]
In my gcode sender, I have an editor where I can select lines and have those lines highlighted in a visualizer. Internally I do this by generating a simple CSV intermediate file: "original line, processed line, parsed comment, line number". The visualizer uses this intermedia tagging each line segment with a line number from the file.

If there was a way to output the line number which generated each gcode command I could create a GSharp editor with a visualizer that displayed lines as the script is edited.

One way to implement this might be a new option to the cli: `g#2g <input> <output> <format>`, where format might look like: `%line_number%, %g_code%`.

In the screenshot below I've highlighted all the lines which make up the spiral

<img width="914" alt="screen shot 2016-06-09 at 9 42 13 pm" src="https://cloud.githubusercontent.com/assets/125509/15952108/1f4dae74-2e8c-11e6-86ba-2bdf5592216f.png">

**Comment by NRSoft** [comment]
Just to clarify which line numbers you want to be returned.

Let's take more simple example of regular polygons. The G# code will look something like this (e.g. octagon, line numbers are for the reference only):

```
(1) #1=8 (sides)
(2) #2=[360/#1] (angle step)
(3) #3=25 (circumference radius)
(4) o100 while [#1 GE 0]
(5) G1 X[#3*cos[#1*#2]] Y[#3*sin[#1*#2]]
(6) #1=[#1-1]
(7) o100 endwhile
```

The output of the interpreter after calling Step() 9 times until finished will be:

```
(1) G1 X25 Y0
(2) G1 X17.678 Y-17.678
(3) G1 X0 Y-25
(4) G1 X-17.678 Y-17.678
(5) G1 X-25 Y0
(6) G1 X-17.678 Y17.678
(7) G1 X0 Y25
(8) G1 X17.678 Y17.678
(9) G1 X25 Y0
```

Each line in the output was created from a single line (5) of the input, and this number can be retrieved at each step (essentially it will be the same number 5).

Which lines would you like to highlight in the editor - from the input or the output? If it's the output, then there should be no difference to what you already have now. Lines (1-9) correspond to the complete polygon. And they all could be referenced back to line 5 of the input.

If it's the input, the interpreter has no knowledge of the output until executed. So I guess you could feed the highlighted part of the code into the interpreter, run it, get the output related to the highlighted block and use it in visualizer. But that could be dangerous, for example if the user highlights only lines (2-7), then parameter 1 will be lost and the number of sides will be zero. And what if the highlighted block uses a variable which has been defined somewhere far away?

Actually you may have already solved this issue in your code. What if G91 (relative coordinates) was used somewhere before and it is not highlighted? You probably keep the current state for each part of the code. I guess we could use similar idea here, although it's impossible to keep the state of all 5000 parameters for each output line. It's easier just to run the G# program from the beginning to the end, checking if the returned line number is present in the highlighted block and then feed it into the visualizer. It's very fast anyway.

Will this work? I can already see some minor issues, but I'm frankly opened to suggestions. Maybe I just don't see the use case properly.

(strictly speaking line 1 of the output does not belong to the polygon, but that doesn't change the logic)

**Comment by NRSoft** [comment]
The comment above is if you want to integrate the library into your own code.
If you are simply after changing the output of the "example.cpp", I think it wouldn't be difficult.

**Comment by winder** [comment]
I was going to run the lines through your program in the background. So
using your example the user would see the 7 lines of G# and the visualizer
shows the 9 lines of Gcode. If they highlight line 5 everything in the
visualizer would be marked.

To be more precise, each line of the interpreter output would need to have
"5," added to the front as a link from script to gcode.

In a larger script with multiple paths you could select a subset of the
lines which create output and just the gcode generated by that output would
be marked.

I parse the gcode and normalize it into absolute coordinates and mm units
so that I don't need to keep the state of each point in mind while
rendering each frame.

For a first pass I was just going to run your cli app in the background.
Maybe making a Java binding layer will be useful in the future.

**Comment by NRSoft** [comment]
Ok, I think I know what's the best way to proceed. You are after adding the line number in front of each generated G-code line in order to be used in your application. In this case the change is minimal, just replace line 105 of "example.cpp" and recompile:

```
-            file_out << str << endl;
+            file_out << r.GetCurrentLineNumber() << ", " << str << endl;

```

That should suit your specific purpose and will not forfeit the purpose of the example.

At this moment I'm a bit reluctant to add generic format parameter because 1) it'd require more time and thinking and 2) I haven't got any requests from other people so far. I'd better wait for higher demand and broader requirements.

Yes, I agree, Java binding may be good to add in the future. Maybe you would be able to help here. See how it goes and let me know.
