### ISSUE TITLE
Window compile

### ISSUE THREAD

**Issue by LETARTARE** [NRSoft/GSharp#1]
Hello,
I just found your idea, it is interesting to Grbl .

I tested quickly on :
-  'Vista Pro',
-  'Code::Block svn1816', 
-  and 'Qt5.6 Gnu Gcc 4.62 compiler',

I had to add the definition of ' M_PI ' in ' gsharp_program.h ' to compile the library.
'Example.cpp' generates correctly 'g#2g.exe'. I tested both file 'ngc ' delivery: that's okay.

I do not have time to do more.
Do you have a 'gtest.cbp' ?
Good job.

Cordially.

**Comment by serlich** [comment]
Thanks for testing it on Windows machine!  I really tried to address the shortage of standard Fanuc / LinuxCNC macro-programming capabilities in grbl controllers. Hopefully it can be useful.

M_PI should come from <cmath>, but it may be different on Win version. I will add #ifndef.
Also good to know that it runs on lower than 4.8 GCC version. I will update the readme.

I will create "gtest.cbp", no worries, but compilation is very simple, doesn't even require Makefile. Readme file in "gtest" directory explains it well.

Thanks again,
NR

**Comment by NRSoft** [comment]
Thanks for testing it on Windows machine!

I really tried to address the shortage of standard Fanuc / LinuxCNC macro-programming capabilities in grbl controllers. Hopefully it can be useful.

M_PI should come from "cmath", but it may be different on Win version. I will add #ifndef.
Also good to know that it runs on lower than 4.8 GCC version. I will update the readme.

I will create "gtest.cbp", no worries, but compilation is very simple, doesn't even require Makefile. Readme file in "gtest" directory explains it well.

Thanks again,
NR

**Comment by LETARTARE** [comment]
Hello,
For Gcc :  'Qt5.6 Gnu Gcc 4.92 compiler' !! Its'a typo.
Bye.
