### ISSUE TITLE
Project files for Windows build

### ISSUE THREAD

**Issue by NRSoft** [NRSoft/GSharp#2]
Currently the library provides only Makefile and Code::Blocks project files. It may be useful to create a Visual Studio project file for building and testing the library under Windows.

**Comment by winder** [comment]
@NRSoft to make the project more portable you could use something like CMake. It's been a while, but I should still be able to set one up if its something you'd be interested in. Basically CMake is a project generator, on my mac it has the following targets, on windows it would have several visual studio projects as well:

> The following generators are available on this platform:
>   Unix Makefiles               = Generates standard UNIX makefiles.
>   Ninja                        = Generates build.ninja files.
>   Xcode                        = Generate Xcode project files.
>   CodeBlocks - Ninja           = Generates CodeBlocks project files.
>   CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
>   CodeLite - Ninja             = Generates CodeLite project files.
>   CodeLite - Unix Makefiles    = Generates CodeLite project files.
>   Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
>   Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
>   KDevelop3                    = Generates KDevelop 3 project files.
>   KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.
>   Kate - Ninja                 = Generates Kate project files.
>   Kate - Unix Makefiles        = Generates Kate project files.
>   Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
>   Sublime Text 2 - Unix Makefiles
>                                = Generates Sublime Text 2 project files.

**Comment by NRSoft** [comment]
@winder I think you're right. I haven't used CMake for my source code before, but now could be good time to start. Could you please create a new issue, or otherwise I could just copy-paste your above comment as the new issue description.
I will close this one because it's been fixed for Windows specific target.
